definitions:
  github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      details:
        example:
        - invalid email
        items:
          type: string
        type: array
      message:
        example: status bad request
        type: string
    type: object
  github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      details:
        example:
        - invalid email
        items:
          type: string
        type: array
      message:
        example: status bad request
        type: string
    type: object
  models.Client:
    properties:
      email:
        description: Email of this client
        type: string
      name:
        description: Name of this client
        type: string
      password:
        description: Password of this client
        type: string
      subscriptions:
        description: Subscriptions that this client has
        items:
          $ref: '#/definitions/models.ClientSubscription'
        type: array
    type: object
  models.ClientSubscription:
    properties:
      next_dose:
        type: string
      rate:
        type: string
      title:
        type: string
    type: object
  models.Disease:
    properties:
      medicines:
        description: Medicines that can cure this disease
        items:
          type: string
        type: array
      name:
        description: Name of this disease
        type: string
      symptoms:
        description: Symptoms of this disease
        items:
          type: string
        type: array
    type: object
  models.Medicine:
    properties:
      diseases:
        description: Diseases that this medicine can cure
        items:
          type: string
        type: array
      name:
        description: Name of this medicine
        type: string
    type: object
info:
  contact: {}
paths:
  /bookkeeping/medicines:
    post:
      consumes:
      - application/json
      description: Create a Medicine in the Database using the data sent by them (REGISTER)
      parameters:
      - description: Medicine details to be created
        in: body
        name: medicineDTO
        required: true
        schema:
          $ref: '#/definitions/models.Medicine'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
      summary: Create a Medicine
      tags:
      - /bookkeeping/medicines
  /bookkeeping/medicines/:
    get:
      consumes:
      - application/json
      description: Fetches all Medicines in database from repository and return an
        unfiltered JSON array of them.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Medicine'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
      summary: Return all Medicines in database from repository.
      tags:
      - /bookkeeping/medicines
  /bookkeeping/medicines/{id}:
    get:
      consumes:
      - application/json
      description: Get a Medicine from the database by its name.
      parameters:
      - description: ID of the Medicine (currently its name)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Medicine'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
      summary: Get a Medicine by its name.
      tags:
      - /bookkeeping/medicines
  /bookkeeping/medicines/{name}:
    delete:
      consumes:
      - application/json
      description: Deletes the Medicine in the Database using their email.
      parameters:
      - description: ID of the Disease (currently its name)
        in: path
        name: diseaseName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Medicine'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
      summary: Deletes Medicines in the Database.
      tags:
      - /bookkeeping/medicines
    put:
      consumes:
      - application/json
      description: Updates the Medicine in the Database using their email.
      parameters:
      - description: Medicine details to be created
        in: body
        name: medicineDTO
        required: true
        schema:
          $ref: '#/definitions/models.Medicine'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Medicine'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
      summary: Updates Medicines in the Database.
      tags:
      - /bookkeeping/medicines
  /bookkeeping/medicines/disease/{diseaseName}:
    get:
      consumes:
      - application/json
      description: Find all medicines for a Disease identified by the disease name
        from the two databases.
      parameters:
      - description: ID of the Disease (currently its name)
        in: path
        name: diseaseName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Medicine'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_bookkeeping_service_models_dtos.HTTPError'
      summary: Find all medicines for a Disease identified by its name.
      tags:
      - /bookkeeping/medicines
  /users/clients:
    post:
      consumes:
      - application/json
      description: Create a Client in the Database using the data sent by them (REGISTER)
      parameters:
      - description: User DTO
        in: body
        name: clientDTO
        required: true
        schema:
          $ref: '#/definitions/models.Client'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
      summary: Create a Client
      tags:
      - /users/clients
  /users/clients/{email}:
    delete:
      consumes:
      - application/json
      description: Deletes the Clients in the Database using their email.
      parameters:
      - description: User Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
      summary: Deletes Clients in the Database.
      tags:
      - /users/clients
    get:
      consumes:
      - application/json
      description: Get a Client from the Database using their email.
      parameters:
      - description: User Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
      summary: Get a Client from Database.
      tags:
      - /users/clients
    put:
      consumes:
      - application/json
      description: Updates the Client in the Database using their email.
      parameters:
      - description: User DTO
        in: body
        name: clientDTO
        required: true
        schema:
          $ref: '#/definitions/models.Client'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
      summary: Updates Clients in the Database.
      tags:
      - /users/clients
  /users/experts/diagnose:
    post:
      consumes:
      - application/json
      description: Sends a Disease Diagnosis using Kafka to the bookkeeping_service
      parameters:
      - description: The Diagnosed Disease
        in: body
        name: disease
        required: true
        schema:
          $ref: '#/definitions/models.Disease'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_dhi13man_healthcare-app_users_service_models_dtos.HTTPError'
      summary: Make Disease Diagnosis by expert to the bookkeeping_service.
      tags:
      - /users/experts/diagnose
swagger: "2.0"
