definitions:
  models.Purchased:
    properties:
      arrival:
        type: string
      arrival_time:
        type: string
      cost:
        type: integer
      departure:
        type: string
      departure_time:
        type: string
      trainid:
        type: string
      userid:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: swiggyb3053@datascience.manipal.edu
    name: Aryann Dhir
    url: http://www.swagger.io/support
  description: Swagger Train Reservation System API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Train Reservation System API
  version: "1.0"
paths:
  /purchase:
    post:
      consumes:
      - application/json
      description: Purchase Ticket by providing ticket details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Purchased'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Purchase A Ticket
      tags:
      - user
  /purchase/:purchasedid:
    delete:
      consumes:
      - application/json
      description: Delete Purchased Ticket by providing ticket id
      parameters:
      - description: purchase unique id
        in: body
        name: purchasedid
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Purchased'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Delete a Purchased Ticket
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Get Purchased Ticket by providing ticket id
      parameters:
      - description: purchase unique id
        in: body
        name: purchasedid
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Purchased'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Fetch a Purchased Ticket
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
