host: localhost:8084
info:
  contact:
    email: chahatbhatia2014@gmail.com
    name: Chahat Bhatia
  description: This microservice is for track stream module in the online shopping
    application.
  license:
    name: Apache 2.0
  title: Online Shopping Application -Track Stream Module
  version: "1.0"
paths:
  /getTrackingData:
    get:
      consumes:
      - application/json
      description: This request will give analytics data of different types of payment.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Get the analytics of application(This usecase tracks the count of different
        modes of payments)
      tags:
      - TrackStream
securityDefinitions:
  Bearer Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
