definitions:
  models.Appointment:
    properties:
      doctorID:
        type: string
      fees:
        type: integer
      generalUserID:
        type: string
      id:
        type: string
      occupied:
        type: boolean
      slot:
        type: string
    type: object
  models.GeneralUser:
    properties:
      address:
        type: string
      age:
        type: integer
      appointments:
        items:
          $ref: '#/definitions/models.Appointment'
        type: array
      emailId:
        type: string
      id:
        type: string
      isPatient:
        type: boolean
      name:
        type: string
      password:
        type: string
      previousDisease:
        type: string
    required:
    - address
    - age
    - emailId
    - name
    - password
    - previousDisease
    type: object
host: localhost:8083
info:
  contact:
    email: aadityakhetan123@gmail.com
    name: Aaditya Khetan
  description: This microservice is for general user module in the sanitaria application.
  license:
    name: Apache 2.0
  title: Sanitaria - GeneralUser Module
  version: "1.0"
paths:
  /generalUser/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a generalUser.
      parameters:
      - description: GeneralUser id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      security:
      - Bearer Token: []
      summary: Delete generalUser by ID.
      tags:
      - GeneralUser
    get:
      consumes:
      - application/json
      description: View all the details of a generalUser.
      parameters:
      - description: GeneralUser id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GeneralUser'
        "500":
          description: Internal Server Error
          schema:
            type: number
      security:
      - Bearer Token: []
      summary: Get generalUser by ID.
      tags:
      - GeneralUser
    put:
      consumes:
      - application/json
      description: Edit details of a generalUser.
      parameters:
      - description: GeneralUser id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GeneralUser'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      security:
      - Bearer Token: []
      summary: Edit generalUser by ID.
      tags:
      - GeneralUser
  /generalUserLogin:
    post:
      consumes:
      - application/json
      description: This request will login a generalUser.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: number
        "404":
          description: Not Found
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: User login for a generalUser profile.
      tags:
      - GeneralUser
  /generalUserRegistration:
    post:
      consumes:
      - application/json
      description: This request will create a new generalUser profile for a user.
      parameters:
      - description: General user details
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.GeneralUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.GeneralUser'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: To register a new generalUser in the sanitaria application
      tags:
      - GeneralUser
  /generalUsers:
    get:
      consumes:
      - application/json
      description: Get details of all generalUsers.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.GeneralUser'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: number
      security:
      - Bearer Token: []
      summary: Get all generalUsers list.
      tags:
      - GeneralUser
securityDefinitions:
  Bearer Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
