definitions:
  dtos.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      details:
        example:
        - invalid email
        items:
          type: string
        type: array
      message:
        example: status bad request
        type: string
    type: object
  models.Client:
    properties:
      email:
        description: Email of this client
        type: string
      name:
        description: Name of this client
        type: string
      subscriptions:
        description: Subscriptions that this client has
        items:
          $ref: '#/definitions/models.ClientSubscription'
        type: array
    type: object
  models.ClientSubscription:
    properties:
      next_dose:
        type: string
      rate:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/clients:
    post:
      consumes:
      - application/json
      description: Create a Client in the Database using the data sent by them (REGISTER)
      parameters:
      - description: User Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: User Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.HTTPError'
      summary: Create a Client
      tags:
      - accounts
  /users/clients/{email}:
    delete:
      consumes:
      - application/json
      description: Deletes the Clients in the Database using their email.
      parameters:
      - description: User Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: User Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.HTTPError'
      summary: Deletes Clients in the Database.
      tags:
      - accounts
    get:
      consumes:
      - application/json
      description: Get a Client from the Database using their email.
      parameters:
      - description: User Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.HTTPError'
      summary: Get a Client from Database.
      tags:
      - accounts
    put:
      consumes:
      - application/json
      description: Updates the Client in the Database using their email.
      parameters:
      - description: User Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: User Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dtos.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.HTTPError'
      summary: Updates Clients in the Database.
      tags:
      - accounts
swagger: "2.0"
