definitions:
  models.Ticket:
    properties:
      arrival_time:
        type: string
      capacity:
        type: integer
      cost:
        type: integer
      departure_time:
        type: string
      id:
        type: string
      trainid:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: swiggyb3053@datascience.manipal.edu
    name: Aryann Dhir
    url: http://www.swagger.io/support
  description: Swagger Train Reservation System API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Train Reservation System API
  version: "1.0"
paths:
  /ticket:
    post:
      consumes:
      - application/json
      description: Create Ticket by providing ticket details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Ticket'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Create A Ticket
      tags:
      - user
  /ticket/:ticketid:
    delete:
      consumes:
      - application/json
      description: Delete Ticket by providing ticket id
      parameters:
      - description: ticket unique id
        in: body
        name: ticketid
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Ticket'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Delete a Ticket
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Get Ticket by providing ticket id
      parameters:
      - description: ticket unique id
        in: body
        name: ticketid
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Ticket'
        "400":
          description: Bad Request
          schema:
            type: number
        "500":
          description: Internal Server Error
          schema:
            type: number
      summary: Fetch a Ticket
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
